export enum KeyTable {
  ID = 'userId',
  Name = 'name',
  CreateBy = 'createdBy',
  CreateOn = 'creationTime',
  Status = 'statusName',
}

export const headerOption = [
  { name: 'ID', width: 30, key: KeyTable.ID },
  { name: 'User Name', width: 280, key: KeyTable.Name },
  { name: 'Created By', width: 130, key: KeyTable.CreateBy },
  { name: 'Created On', width: 120, key: KeyTable.CreateOn },
  { name: 'Status', width: 120, key: KeyTable.Status },
]

export const dataList = [
  {
    id: 1,
    userId: '1',
    name: 'Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.',
    createdBy: 'Kally Fearey',
    createOn: '1/1/2022',
    status: 'Pending',
  },
  {
    id: 2,
    userId: '2',
    name: 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.',
    createdBy: 'Nicolle Northwood',
    createOn: '3/3/2021',
    status: 'Pending',
  },
  {
    id: 3,
    userId: '3',
    name: 'Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue.',
    createdBy: 'Ceil Obbard',
    createOn: '8/15/2021',
    status: 'Draft',
  },
  {
    id: 4,
    userId: '4',
    name: 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh.',
    createdBy: 'Estrellita Nathon',
    createOn: '6/23/2021',
    status: 'Finished',
  },
  {
    id: 5,
    userId: '5',
    name: 'Integer ac neque. Duis bibendum.',
    createdBy: 'Emanuel Lowdwell',
    createOn: '3/2/2021',
    status: 'Finished',
  },
  {
    id: 6,
    userId: '6',
    name: 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.',
    createdBy: 'Yetty Mussalli',
    createOn: '6/14/2021',
    status: 'Pending',
  },
  {
    id: 7,
    userId: '7',
    name: 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.',
    createdBy: 'Georgette Pfiffer',
    createOn: '5/4/2021',
    status: 'Finished',
  },
  {
    id: 8,
    userId: '8',
    name: 'Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.',
    createdBy: 'Cissy Aggiss',
    createOn: '2/8/2021',
    status: 'In Progress',
  },
  {
    id: 9,
    userId: '9',
    name: 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.',
    createdBy: 'Olenolin Firpo',
    createOn: '10/14/2021',
    status: 'Pending',
  },
  {
    id: 10,
    userId: '10',
    name: 'Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.',
    createdBy: 'Kylynn Tucknutt',
    createOn: '4/9/2021',
    status: 'Finished',
  },
  {
    id: 11,
    userId: '11',
    name: 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.',
    createdBy: 'Judy Ellings',
    createOn: '10/11/2021',
    status: 'Pending',
  },
  {
    id: 12,
    userId: '12',
    name: 'Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.',
    createdBy: 'Emili Endean',
    createOn: '5/29/2021',
    status: 'Finished',
  },
  {
    id: 13,
    userId: '13',
    name: 'Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti.',
    createdBy: 'Kennedy Vigne',
    createOn: '4/15/2021',
    status: 'Pending',
  },
  {
    id: 14,
    userId: '14',
    name: 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius.',
    createdBy: 'Haslett Witham',
    createOn: '9/3/2021',
    status: 'Finished',
  },
  {
    id: 15,
    userId: '15',
    name: 'Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.',
    createdBy: 'Cynde Gaythorpe',
    createOn: '8/22/2021',
    status: 'Finished',
  },
  {
    id: 16,
    userId: '16',
    name: 'Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.',
    createdBy: 'Jodie Fairlem',
    createOn: '4/9/2021',
    status: 'Draft',
  },
  {
    id: 17,
    userId: '17',
    name: 'Pellentesque ultrices mattis odio. Donec vitae nisi.',
    createdBy: 'Annabal Kubal',
    createOn: '12/8/2021',
    status: 'In Progress',
  },
  {
    id: 18,
    userId: '18',
    name: 'Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.',
    createdBy: 'Martie McAdam',
    createOn: '9/3/2021',
    status: 'Draft',
  },
  {
    id: 19,
    userId: '19',
    name: 'In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna.',
    createdBy: 'Evonne Leahy',
    createOn: '11/2/2021',
    status: 'Pending',
  },
  {
    id: 20,
    userId: '20',
    name: 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.',
    createdBy: 'Norris Bertholin',
    createOn: '11/17/2021',
    status: 'Pending',
  },
]
